-- Books from BOOKS.pdf not previously in the database
-- Auto-generated by scripts/add-books-from-pdf.ts (titles/URLs hand-corrected)

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Change', 'John P. Kotter, Vanessa Akhtar, Gaurav Gupta', 'https://openlibrary.org/works/OL1932148W', 'https://covers.openlibrary.org/b/id/668100-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Change-Maker', 'Maria Giudice & Christopher Ireland', 'https://openlibrary.org/works/OL28846072W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Click: Ten Truths for Building Extraordinary Relationships', 'George C. Fraser', 'https://openlibrary.org/works/OL2716263W', 'https://covers.openlibrary.org/b/id/2316287-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Corporate Rebels', 'Joost Minnaar & Pim de Morree', 'https://openlibrary.org/works/OL24316005W', 'https://covers.openlibrary.org/b/id/10833742-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Delivering Happiness', 'Tony Hsieh', 'https://openlibrary.org/works/OL15582623W', 'https://covers.openlibrary.org/b/id/6956287-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Drive', 'Daniel H. Pink', 'https://openlibrary.org/works/OL15016965W', 'https://covers.openlibrary.org/b/id/6404786-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Engaged: Designing for Behavior Change', 'Amy Bucher', 'https://openlibrary.org/works/OL20872173W', 'https://covers.openlibrary.org/b/id/10192441-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Farther Faster and Far Less Drama', 'Janice Fraser & Jason Fraser', 'https://openlibrary.org/works/OL28727935W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Games People Play', 'Eric Berne M.D.', 'https://openlibrary.org/works/OL1593567W', 'https://covers.openlibrary.org/b/id/8281189-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('How to Win Friends and Influence People', 'Dale Carnegie', 'https://openlibrary.org/works/OL1063267W', 'https://covers.openlibrary.org/b/id/13314878-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Influence Is Your Superpower', 'Zoe Chance', 'https://openlibrary.org/works/OL26335776W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Lean Enterprise', 'Jez Humble, Joanne Molesky & Barry O''Reilly', 'https://openlibrary.org/works/OL21514240W', 'https://covers.openlibrary.org/b/id/11947016-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Liminal Thinking', 'Dave Gray', 'https://openlibrary.org/works/OL19085883W', 'https://covers.openlibrary.org/b/id/8401581-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Multipliers', 'Liz Wiseman', 'https://openlibrary.org/works/OL18569599W', 'https://covers.openlibrary.org/b/id/9265081-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Navigating the Politics of UX', 'John Scott Bowie', 'https://openlibrary.org/works/OL26955203W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Negotiation Genius', 'Deepak Malhotra & Max Bazerman', 'https://openlibrary.org/works/OL12284504W', 'https://covers.openlibrary.org/b/id/374240-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Never Split the Difference', 'Chris Voss', 'https://openlibrary.org/works/OL18819818W', 'https://covers.openlibrary.org/b/id/8365942-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('One Mission', 'Chris Fussell', 'https://openlibrary.org/works/OL20218951W', 'https://covers.openlibrary.org/b/id/8871007-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Post-Capitalist Society', 'Peter F. Drucker', 'https://openlibrary.org/works/OL10476692W', 'https://covers.openlibrary.org/b/id/10028290-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Present Yourself', 'Danielle Barnes & Christina Wodtke', NULL, NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Rise of the DEO', 'Maria Giudice & Christopher Ireland', NULL, NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Rituals Roadmap', 'Erica Keswin', 'https://openlibrary.org/works/OL21961936W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Social Chemistry', 'Marissa King', 'https://openlibrary.org/works/OL20749207W', 'https://covers.openlibrary.org/b/id/11065836-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Speak-Up Culture', 'Stephen Shedletzky', NULL, NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Start-Up Factory', 'Joost Minnaar & Pim de Morree', NULL, NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Team of Teams', 'Gen. Stanley McChrystal', 'https://openlibrary.org/works/OL20000938W', 'https://covers.openlibrary.org/b/id/10522497-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Big Leap', 'Gay Hendricks', 'https://openlibrary.org/works/OL14950936W', 'https://covers.openlibrary.org/b/id/6305214-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Coaching Habit', 'Michael Bungay Stanier', 'https://openlibrary.org/works/OL20038440W', 'https://covers.openlibrary.org/b/id/12515817-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Creative Act', 'Rick Rubin', 'https://openlibrary.org/works/OL27955361W', 'https://covers.openlibrary.org/b/id/13316390-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Gervais Principle', 'Venkatesh Rao', 'https://openlibrary.org/works/OL28670515W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Goal', 'Eliyahu M. Goldratt & Jeff Cox', 'https://openlibrary.org/works/OL2463054W', 'https://covers.openlibrary.org/b/id/682721-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Happiness Track', 'Emma Seppälä PhD', 'https://openlibrary.org/works/OL20023899W', 'https://covers.openlibrary.org/b/id/8844498-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('The Toyota Way to Lean Leadership', 'Jeffrey Liker & Gary Convis', 'https://openlibrary.org/works/OL16184012W', NULL, 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Thinking, Fast and Slow', 'Daniel Kahneman', 'https://openlibrary.org/works/OL15992072W', 'https://covers.openlibrary.org/b/id/13290711-M.jpg', 5, 'book', 'manual', 'published');

INSERT INTO resources (title, author, url, image_url, category_id, type, source, status)
VALUES ('Turn the Ship Around!', 'L. David Marquet', 'https://openlibrary.org/works/OL17845539W', 'https://covers.openlibrary.org/b/id/8142531-M.jpg', 5, 'book', 'manual', 'published');

-- 11 books without Open Library covers (to be resolved separately):
-- Change-Maker, Farther Faster and Far Less Drama, Influence Is Your Superpower,
-- Navigating the Politics of UX, Present Yourself, Rise of the DEO, Rituals Roadmap,
-- Speak-Up Culture, Start-Up Factory, The Gervais Principle, The Toyota Way to Lean Leadership
