-- Auto-generated by scripts/update-book-covers.ts
-- Replaces book cover URLs with Open Library covers

UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/10213391-M.jpg' WHERE id = 61;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/9700992-M.jpg' WHERE id = 163;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/8805106-M.jpg' WHERE id = 165;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/8854703-M.jpg' WHERE id = 166;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/10863273-M.jpg' WHERE id = 168;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/9602663-M.jpg' WHERE id = 169;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/2555094-M.jpg' WHERE id = 170;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/8667291-M.jpg' WHERE id = 171;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/9262333-M.jpg' WHERE id = 172;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/7367250-M.jpg' WHERE id = 174;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/11945339-M.jpg' WHERE id = 175;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/6395237-M.jpg' WHERE id = 177;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/10470266-M.jpg' WHERE id = 178;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/7391212-M.jpg' WHERE id = 179;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/10169974-M.jpg' WHERE id = 180;
UPDATE resources SET image_url = 'https://covers.openlibrary.org/b/id/12003050-M.jpg' WHERE id = 183;

-- No cover found on Open Library:
-- 60: The Design Conductors
-- 62: Org Design for Design Orgs
-- 63: What Is DesignOps
-- 167: Design Leadership
-- 181: Authentic Leadership
-- 182: Make Your Own Map