/**
 * Replace book cover image_url with Open Library covers where available.
 * Uses the Open Library search API to find covers by title+author.
 *
 * Run: node scripts/update-book-covers.ts
 * Then apply: npx wrangler d1 execute design-resources --remote --file=db/seed/update-book-covers.sql
 */

import { writeFileSync } from "fs";

interface OLSearchResult {
  numFound: number;
  docs: Array<{
    title?: string;
    cover_i?: number;
    author_name?: string[];
  }>;
}

const books = [
  { id: 60,  title: "The Design Conductors",              author: "Richard Banfield" },
  { id: 61,  title: "Liftoff",                            author: "Chris Avore" },
  { id: 62,  title: "Org Design for Design Orgs",        author: "Peter Merholz" },
  { id: 63,  title: "What Is DesignOps",                  author: "Meredith Black" },
  { id: 163, title: "Simply Said",                        author: "Jay Sullivan" },
  { id: 165, title: "The Making of a Manager",            author: "Julie Zhuo" },
  { id: 166, title: "HBR 10 Must Reads for New Managers", author: "Harvard Business Review" },
  { id: 167, title: "Design Leadership",                  author: "Richard Banfield" },
  { id: 168, title: "The Five Dysfunctions of a Team",    author: "Patrick Lencioni" },
  { id: 169, title: "Resilient Management",               author: "Lara Hogan" },
  { id: 170, title: "Difficult Conversations",             author: "Douglas Stone" },
  { id: 171, title: "The Manager's Path",                 author: "Camille Fournier" },
  { id: 172, title: "The Advantage",                      author: "Patrick Lencioni" },
  { id: 174, title: "Dare to Lead",                       author: "Brené Brown" },
  { id: 175, title: "Atlas of the Heart",                 author: "Brené Brown" },
  { id: 177, title: "Start with Why",                     author: "Simon Sinek" },
  { id: 178, title: "Think Again",                        author: "Adam Grant" },
  { id: 179, title: "Give and Take",                      author: "Adam Grant" },
  { id: 180, title: "Just Work",                          author: "Kim Scott" },
  { id: 181, title: "Authentic Leadership",               author: "Karisa Kaye" },
  { id: 182, title: "Make Your Own Map",                  author: "Kathryn Bishop" },
  { id: 183, title: "Bittersweet",                        author: "Susan Cain" },
];

async function findCover(title: string, author: string): Promise<string | null> {
  const q = encodeURIComponent(`${title} ${author}`);
  const url = `https://openlibrary.org/search.json?q=${q}&fields=title,cover_i,author_name&limit=5`;
  const res = await fetch(url, { headers: { "User-Agent": "design-resources-script/1.0" } });
  if (!res.ok) return null;
  const data = (await res.json()) as OLSearchResult;
  const hit = data.docs.find((d) => d.cover_i);
  return hit?.cover_i ? `https://covers.openlibrary.org/b/id/${hit.cover_i}-M.jpg` : null;
}

async function main() {
  const updates: string[] = [];
  const skipped: string[] = [];

  for (const book of books) {
    process.stdout.write(`  Looking up: ${book.title}... `);
    await new Promise((r) => setTimeout(r, 300)); // be polite to OL rate limits
    const coverUrl = await findCover(book.title, book.author);
    if (coverUrl) {
      console.log(`✓`);
      updates.push(`UPDATE resources SET image_url = '${coverUrl}' WHERE id = ${book.id};`);
    } else {
      console.log(`✗ no cover found`);
      skipped.push(`-- ${book.id}: ${book.title}`);
    }
  }

  const sql = [
    "-- Auto-generated by scripts/update-book-covers.ts",
    "-- Replaces book cover URLs with Open Library covers",
    "",
    ...updates,
    "",
    ...(skipped.length ? ["-- No cover found on Open Library:", ...skipped] : []),
  ].join("\n");

  writeFileSync("db/seed/update-book-covers.sql", sql);
  console.log(`\nWrote db/seed/update-book-covers.sql  (${updates.length} updated, ${skipped.length} skipped)`);
}

main();
